### ISSUE TITLE
Store dependency file as JSON

### ISSUE THREAD

**Issue by roberth** [fzakaria/mvn2nix#10]
Currently the dependencies are stored in Nix syntax, but this doesn't seem to be a requirement.
By changing the format to JSON, `mvn2nix` could appeal to a wider audience.

`builtins.fromJSON (builtins.readFile x)` behaves generally similar to `import x` (modulo format of course), except Nix has a cache for parsed `imports` which is probably counterproductive anyway for memory footprint :man_shrugging:.

**Comment by fzakaria** [comment]
I considered this; it would make the implementation simpler too.
I could rely on a wide variety of JSON libraries.

There was something appealing though about writing pure Nix.
I'm open to change or contribution.
