### ISSUE TITLE
java.lang.RuntimeException: Could not find artifact decentralized-identity:jsonld-common-java:jar:0.2.0 in any repository

### ISSUE THREAD

**Issue by humancalico** [fzakaria/mvn2nix#40]
I tried generating the Nix dependencies file using `nix run github:fzakaria/mvn2nix#mvn2nix > mvn2nix-lock.json` for https://github.com/decentralized-identity/universal-resolver but got this error
```
java.lang.RuntimeException: Could not find artifact decentralized-identity:jsonld-common-java:jar:0.2.0 in any repository
```

**Comment by fzakaria** [comment]
The current version doesn't read your pom.xml or ~/.m2/settings.xml for what repositories you might setup.
You have to provide it over the CLI for now (it's an improvement that should be made)

**Comment by humancalico** [comment]
> You have to provide it over the CLI for now

I'm not sure how to do that

**Comment by fzakaria** [comment]
There should be a `--help` function.

For reference:
https://github.com/fzakaria/mvn2nix/blob/master/src/main/java/com/fzakaria/mvn2nix/cmd/Maven2nix.java#L54

**Comment by humancalico** [comment]
Thanks!

**Comment by humancalico** [comment]
Somehow when I run the same command on https://github.com/decentralized-identity/universal-registrar which has the same repositories https://github.com/decentralized-identity/universal-registrar/blob/70b183a92eb885ecfb19cd2aebacbc8600ade468/pom.xml#L48-L64 it seems to work just fine

**Comment by fzakaria** [comment]
Could be a bug where I'm only adding to the normal repositories and not
SNAPSHOT.
I can look into it.

Ideally though you shouldn't be building projects with SNAPSHOT in Nix
since it's not going to be reproducible (no guarantee they persist I think).


Farid Zakaria

**Comment by tshaynik** [comment]
Hi, I'm having a very similar issue, with some SNAPSHOT dependencies not resolving, which seems to confirm your hypothesis that there's a bug.

```
java.lang.RuntimeException: Could not find artifact dnsjava:dnsjava:pom:2.1.7-jitsi-1-SNAPSHOT in any repository
```
I confirmed that it is present in the repository in question: https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/dnsjava/dnsjava/2.1.7-jitsi-1-SNAPSHOT

I definitely agree that not using SNAPSHOTs would be much better, but having mvn2nix add them (or fail more gracefully when confronted with them) would be a big help for the situation I'm currently finding myself in!

**Comment by fzakaria** [comment]
Can you make me a minimal pom.xml to test and reproduce?

**Comment by fzakaria** [comment]
Okay here is my minimal repro:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.fzakaria</groupId>
    <artifactId>mvn2nix-test</artifactId>
    <version>0.1</version>

    <properties>
    </properties>

	<repositories>
		<repository>
			<id>danubetech-maven-public</id>
			<url>https://repo.danubetech.com/repository/maven-public/</url>
		</repository>
        <repository>
			<id>danubetech-maven-snapshots</id>
			<url>https://repo.danubetech.com/repository/maven-snapshots/</url>
		</repository>
	</repositories>
    
    <dependencies>
        <!-- MAVEN START -->
        <dependency>
            <groupId>decentralized-identity</groupId>
            <artifactId>did-common-java</artifactId>
            <version>0.3-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>
```

The error is that my code expects the JAR downloaded to be `did-common-java-0.3-SNAPSHOT.jar`; in fact such a JAR exists.
Unfortunately, the JAR on the artifactory has the timestamp embedded within it.

```bash
❯ tree .
.
└── 0.3-SNAPSHOT
    ├── did-common-java-0.3-20210721.083123-35.jar
    ├── did-common-java-0.3-20210721.083123-35.jar.sha1
    ├── did-common-java-0.3-20210721.083123-35.pom
    ├── did-common-java-0.3-20210721.083123-35.pom.sha1
    ├── did-common-java-0.3-SNAPSHOT.jar
    ├── did-common-java-0.3-SNAPSHOT.pom
    ├── maven-metadata-danubetech-maven-public.xml
    ├── maven-metadata-danubetech-maven-public.xml.sha1
    ├── maven-metadata-danubetech-maven-snapshots.xml
    ├── maven-metadata-danubetech-maven-snapshots.xml.sha1
    ├── _remote.repositories
    └── resolver-status.properties
```
https://repo.danubetech.com/service/rest/repository/browse/maven-snapshots/decentralized-identity/did-common-java/0.3-SNAPSHOT/0.3-20201030.084016-1/

This is quite complex handling that is not accounted for at the moment.
It's not 100% clear to me whether we can just ignore `-SNAPSHOT` one and try to find the timestamped out since that can be disabled by the author [https://maven.apache.org/plugins-archives/maven-deploy-plugin-2.6/examples/disabling-timestamps-suffix.html]

The fact that it **can be disabled** is the whole reason why we should not allow timestamps.
I believe the approach here should be one similar to nixpkgs and a patch should be applied to fix it to a specific version.

**Comment by humancalico** [comment]
@fzakaria Hey, can you open another issue regarding this?

**Comment by fzakaria** [comment]
It's the same issue; but do you mean one specifically calling out the missing feature support of SNAPSHOT ?

**Comment by humancalico** [comment]
> but do you mean one specifically calling out the missing feature support of SNAPSHOT ?

Yeah
