### ISSUE TITLE
Error: "Too many open files" custom project.

### ISSUE THREAD

**Issue by PlumpMath** [fzakaria/mvn2nix#44]
https://discourse.nixos.org/t/should-i-force-all-package-derivation-to-flake-way-y-y-too-many-open-files/16299/4

Recently changed to flake, I'm not sure how to approach it.
I don't use nix-shell so...
Just ignorantly, one shot, ~/.config/nixpkgs/config.nix
Managed by Hankyu...
I tend to create and manage a nix file containing mkDerivation myself.

 **Too many open files**
 
 Because of this error, all the package groupings in my config.nix file were split at once, but the json file created with mvn2nix is too large,
I keep getting this error, I don't know how to split this...

And, I have one question.
.
Other than console.. I mainly use clojure, but I am also thinking a lot about interop with java.
So I don't know about maven, but since the company project is made of jsp, I want to merge it someday.
therefore,
I wonder if tomcat jsp can also be managed with mvn2nix. If that is possible, should I create a project template created in maven as eclipse and apply mvn2nix ?

Thanks.

**Comment by pasqui23** [comment]
Can confirm this happen also on a Ubuntu machine with a Spring Boot project.

**Comment by PlumpMath** [comment]
As I remember, if I reduce the dependent packages one by one, there are times when it gets resolved.

**Comment by pasqui23** [comment]
I've resolved by using the deb package installer from https://nix-community.github.io/nix-installers/ instead of the official nix installer

**Comment by PlumpMath** [comment]
flake.nix

overlays = [
...
# I'm not sure if I need both.
mvn2nix.overlay (import "${mvn2nix}/overlay.nix") 
...
];

environment.systemPackages = [
...
mvn2nix
...
];

deb installer? Is it possible to use deb or rpm pacman on nixos? That's awesome.
.
Basic interop test is planned for clojure java.
I've been playing with clj-nix for a while; The feeling is fine. I'll try and think about which one is more convenient with clj2nix, yet both have the same requirements.

**Comment by pasqui23** [comment]
No, a deb package to install nix

**Comment by PlumpMath** [comment]
Am I see something like brew in nix-darwin?
Is it possible to completely override the original derivation after indicating exactly where it is installed on the apt or rpm side?
Because, I feel that the binary installation method is faster. 
and I don't like to build, 

so I don't want to go back to other linux like ubuntu or redhat linux yet (I love nixos), but I've tried to Install ubuntu use with nix and operate only nix in a place like ubuntu in the past. (Like Mac with nix)
However, these days, the pins for the ones built on MacOS don't work properly, so I'm worried.
I wish brew had something like that.
