### ISSUE TITLE
Retry obtaining artifacts are least a few times

### ISSUE THREAD

**Issue by nagisa** [fzakaria/mvn2nix#52]
A project I’m attempting to build (openhab), I think utilizes repositories that aren’t 100% reliable. As a result I’m getting errors like 

> java.lang.RuntimeException: Could not find artifact org.openhab.addons.bundles:org.openhab.binding.zway:pom:3.4.2 in any repository 

each time with a different package failing. Would it be possible to try the loop of obtaining an artifact a few times before throwing an exception?

Possibly by placing a plain loop around this snippet https://github.com/fzakaria/mvn2nix/blob/ea21cfe97069feee55fa307ca9b125616c1fa84f/src/main/java/com/fzakaria/mvn2nix/cmd/Maven2nix.java#L81-L93? There may be more elaborate approaches, of course.

Happy to attempt a contribution if this sounds okay to you?

**Comment by fzakaria** [comment]
I think the cache approach you have should solve this ?
Maven itself should also retry itself AFAIK when it tries to download.

Can you see looping mvn2nix that way gets you far enough?
I don't want to change too much the code at the moment.

**Comment by nagisa** [comment]
Yeah, the cache approach (I assume this is in reference to https://github.com/fzakaria/mvn2nix/pull/53) works quite well for the purpose of getting to the point of having everything downloaded.
